---
android_setup_enabled: true
android_sdk_root: "{{ ansible_env.HOME }}/Android/Sdk"
android_ndk_version: "28.2.13676358"
android_sdk_api_level: "34"
android_cmdline_tools_version: "10.0"
android_kotlin_version: "2.1.10"
android_kotlin_install_dir: "/usr/lib/kotlinc"
android_java_home: ""
